### ISSUE TITLE
Update to gittools in pipeline

### ISSUE THREAD

**Issue by petervandenhout** [ofpinewood/pineblog#138]
```
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Determine Version
```
